from typing import List, TypedDict, Optional, Literal

RecommendationType = Literal[
    "timing_intervention",
    "substitution",
    "prevention_plan",
    "recovery",
    "soft_intervention",
]

PatternType = Literal[
    "mood_dip_then_eat",
    "late_night_eating_cluster",
    "weekday_weekend_shift",
    "meal_type_mood_association",
    "symptom_correlation",
    "mood_boost",
    "delayed_trigger",
    "energy_dip_trigger",
    "sleep_impact_trigger",
]

ConfidenceLevel = Literal["low", "medium", "high"]
Intensity = Literal["low", "medium", "high"]

class ActionTemplate(TypedDict):
    id: str
    recommendationType: RecommendationType
    applicablePatternTypes: List[PatternType]
    intensity: Intensity
    minPatternConfidence: ConfidenceLevel
    minMealEventsInWindow: int
    minMoodEventsInWindow: int
    tags: List[str]
    category: str
    titleTemplate: str
    summaryTemplate: str
    actionTemplate: str
    whyTemplate: str
    ctaType: Optional[str]
    ctaLabel: Optional[str]
    associatedExperimentId: Optional[str]

ACTION_LIBRARY: List[ActionTemplate] = [
    {
        "id": "p1_soft_pause_60s",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": ["mood_dip_then_eat"],
        "intensity": "low",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 5,
        "category": "behavioral_shift",
        "titleTemplate": "Try a 60-second pause first",
        "summaryTemplate": "A short pause before eating can help you stay mindful when stressed.",
        "actionTemplate": "Next time you notice a low mood or high stress, pause for 60 seconds before eating. Take 5 slow breaths, then decide.",
        "whyTemplate": "Your logs suggest eating often happens soon after a mood dip. A short pause can help you choose intentionally.",
        "ctaType": "start_experiment",
        "ctaLabel": "Try Pause",
        "associatedExperimentId": "stress_reset_60s",
    },
    {
        "id": "p1_timing_delay_10min",
        "recommendationType": "timing_intervention",
        "applicablePatternTypes": ["mood_dip_then_eat"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 7,
        "category": "behavioral_shift",
        "titleTemplate": "Add a 10-minute buffer",
        "summaryTemplate": "Delaying cravings by just 10 minutes can significantly reduce emotional eating.",
        "actionTemplate": "When a craving hits after a mood dip, set a 10-minute timer. If you still want food after the timer, eat without guilt.",
        "whyTemplate": "In your data, snacks often follow stress/low mood quickly. A small buffer can reduce autopilot eating.",
        "ctaType": "log_mood",
        "ctaLabel": "Try Buffer",
        "associatedExperimentId": None,
    },
    {
        "id": "p1_substitute_pairing",
        "recommendationType": "substitution",
        "applicablePatternTypes": ["mood_dip_then_eat"],
        "intensity": "medium",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 7,
        "category": "substitution",
        "titleTemplate": "Use a “pairing” snack",
        "summaryTemplate": "Pairing sweets with fiber or protein stabilizes your blood sugar and mood.",
        "actionTemplate": "If you want something sweet, pair it with something filling (e.g., fruit + yogurt, or a small sweet + nuts).",
        "whyTemplate": "Your logs show mood dips often precede snacking. Pairing can keep the snack satisfying without needing exact tracking.",
        "ctaType": "log_meal",
        "ctaLabel": "Log Pairing",
        "associatedExperimentId": None,
    },
    {
        "id": "p1_prevention_plan_pack_snack",
        "recommendationType": "prevention_plan",
        "applicablePatternTypes": ["mood_dip_then_eat"],
        "intensity": "medium",
        "minPatternConfidence": "high",
        "minMealEventsInWindow": 10,
        "minMoodEventsInWindow": 10,
        "category": "planning",
        "titleTemplate": "Pre-plan one “default” snack",
        "summaryTemplate": "Having a go-to healthy snack ready reduces the chance of stress-eating.",
        "actionTemplate": "Pick one simple default snack for stressful moments and keep it available (same option all week).",
        "whyTemplate": "Your pattern suggests stress → eating within a short window. A default snack reduces decision friction and helps consistency.",
        "ctaType": "set_goal",
        "ctaLabel": "Pick Snack",
        "associatedExperimentId": None,
    },
    {
        "id": "p2_timing_cutoff_soft",
        "recommendationType": "timing_intervention",
        "applicablePatternTypes": ["late_night_eating_cluster"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 0,
        "tags": ["sleep", "timing", "low_friction"],
        "titleTemplate": "Try a gentle kitchen \"close time\"",
        "summaryTemplate": "A soft cutoff time can reduce late-night eating without strict rules or guilt.",
        "actionTemplate": "Pick a realistic kitchen close time (e.g., 9:00 PM) for 3 nights this week. If you eat after it, just log it—no judgment.",
        "whyTemplate": "Your logs show a cluster of late-night eating. A gentle cutoff can reduce the frequency without requiring big changes.",
        "associatedExperimentId": "no_late_snacks",
    },
    {
        "id": "p2_prevention_plan_evening_snack",
        "recommendationType": "prevention_plan",
        "applicablePatternTypes": ["late_night_eating_cluster"],
        "intensity": "medium",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 0,
        "tags": ["planning", "evening"],
        "titleTemplate": "Plan an earlier \"bridge\" snack",
        "summaryTemplate": "A planned snack between dinner and bedtime can prevent the late-night hunger that drives unplanned eating.",
        "actionTemplate": "If late-night hunger is common, plan a small snack 1–2 hours after dinner (same time for a few days).",
        "whyTemplate": "Late-night eating often follows a long gap after dinner. A planned bridge snack can reduce unplanned late-night eating.",
        "associatedExperimentId": None,
    },
    {
        "id": "p2_recovery_sleep_routine",
        "recommendationType": "recovery",
        "applicablePatternTypes": ["late_night_eating_cluster"],
        "intensity": "low",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 0,
        "tags": ["sleep", "recovery"],
        "titleTemplate": "Protect your wind-down routine",
        "summaryTemplate": "A consistent evening wind-down can reduce late-night food impulses and help your body shift toward rest.",
        "actionTemplate": "Set a 15-minute wind-down: dim lights, screens down, and prepare for sleep. If you still want food, choose a light option.",
        "whyTemplate": "Your logs show more late-night eating. A consistent wind-down can reduce late-night impulses and support better rest.",
        "associatedExperimentId": None,
    },
    {
        "id": "p3_timing_anchor_one_meal",
        "recommendationType": "timing_intervention",
        "applicablePatternTypes": ["weekday_weekend_shift"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 10,
        "minMoodEventsInWindow": 0,
        "tags": ["timing", "routine"],
        "titleTemplate": "Anchor one meal time on weekends",
        "summaryTemplate": "Keeping one meal at a consistent time on weekends can stabilize your eating rhythm without strict rules.",
        "actionTemplate": "Pick one meal (breakfast or lunch) to keep within a 1-hour window on weekends for the next 2 weekends.",
        "whyTemplate": "Your logs suggest weekend routines differ from weekdays. Anchoring one meal can stabilize the rest of the day without strict rules.",
        "associatedExperimentId": None,
    },
    {
        "id": "p3_prevention_plan_weekend_snacks",
        "recommendationType": "prevention_plan",
        "applicablePatternTypes": ["weekday_weekend_shift"],
        "intensity": "medium",
        "minPatternConfidence": "high",
        "minMealEventsInWindow": 12,
        "minMoodEventsInWindow": 0,
        "tags": ["planning"],
        "titleTemplate": "Create a weekend snack plan",
        "summaryTemplate": "Your weekend snacking pattern differs from weekdays. A simple plan can reduce unplanned snacking without restricting enjoyment.",
        "actionTemplate": "If weekends have more snacks, choose 1 planned snack time + 1 planned snack option for the weekend.",
        "whyTemplate": "Your data indicates weekend behavior shifts. A simple plan reduces randomness without restricting enjoyment.",
        "associatedExperimentId": None,
    },
    {
        "id": "p4_substitute_high_sugar_swap",
        "recommendationType": "substitution",
        "applicablePatternTypes": ["meal_type_mood_association"],
        "intensity": "medium",
        "minPatternConfidence": "high",
        "minMealEventsInWindow": 12,
        "minMoodEventsInWindow": 8,
        "tags": ["substitution", "energy"],
        "titleTemplate": "Try a lighter swap once",
        "summaryTemplate": "Your logs show a connection between a certain meal type and later mood shifts. One controlled swap this week can reveal whether it makes a difference.",
        "actionTemplate": "If a certain meal type is followed by a mood dip in your logs, try swapping it once this week for a lighter alternative and compare.",
        "whyTemplate": "Your logs show an association between a meal type and later mood changes. A single controlled swap can test what works for you.",
        "associatedExperimentId": None,
    },
    {
        "id": "p4_recovery_after_heavy",
        "recommendationType": "recovery",
        "applicablePatternTypes": ["meal_type_mood_association"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 10,
        "minMoodEventsInWindow": 6,
        "tags": ["recovery", "movement"],
        "titleTemplate": "Add a short reset after heavier meals",
        "summaryTemplate": "Light movement after heavier meals is linked to better mood and energy in your logs. A short walk may ease the post-meal slump.",
        "actionTemplate": "After a heavier meal, take a 10-minute light walk or do gentle movement. Log how you feel 1–2 hours later.",
        "whyTemplate": "Your data suggests certain meals are associated with later mood/energy shifts. A small recovery routine may improve how you feel.",
        "associatedExperimentId": None,
    },
    {
        "id": "safe_soft_hydration",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": [
            "mood_dip_then_eat",
            "late_night_eating_cluster",
            "weekday_weekend_shift",
            "meal_type_mood_association",
        ],
        "intensity": "low",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 0,
        "minMoodEventsInWindow": 0,
        "tags": ["safe", "low_friction"],
        "titleTemplate": "Start with a simple reset",
        "summaryTemplate": "A small reset habit can reduce automatic eating while your logs build up.",
        "actionTemplate": "Before your next snack, drink a glass of water and wait 2 minutes. If you still want food, eat and log it.",
        "whyTemplate": "You’re still building consistent logs. This is a safe, low-effort step while the system learns your patterns.",
        "associatedExperimentId": "hydration_boost",
    },
    {
        "id": "mood_boost_double_down",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": ["mood_boost"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 5,
        "category": "positive_reinforcement",
        "titleTemplate": "Found a mood booster!",
        "summaryTemplate": "Certain foods correlate with better mood for you.",
        "actionTemplate": "We noticed your mood is often better after eating meals with this ingredient. Try having it again when you need a boost!",
        "whyTemplate": "Your logs show a positive correlation. Doubling down on what works is a great way to stay consistent.",
        "ctaType": "log_meal",
        "ctaLabel": "Log Again",
        "associatedExperimentId": None,
    },
    {
        "id": "symptom_trigger_awareness",
        "recommendationType": "prevention_plan",
        "applicablePatternTypes": ["symptom_correlation", "delayed_trigger"],
        "intensity": "medium",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 0,
        "category": "awareness",
        "titleTemplate": "Potential trigger identified",
        "summaryTemplate": "We found a connection between {trigger} and your {symptom}.",
        "actionTemplate": "Next time you have {trigger}, pay close attention to how you feel 0-24 hours later. Awareness is the first step to optimization.",
        "whyTemplate": "Your logs show a recurring pattern. Testing this connection can help you identify what to swap next.",
        "ctaType": "start_experiment",
        "ctaLabel": "Track Closely",
        "associatedExperimentId": None,
    },
    {
        "id": "trigger_substitution_experiment",
        "recommendationType": "substitution",
        "applicablePatternTypes": ["symptom_correlation", "delayed_trigger"],
        "intensity": "medium",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 10,
        "minMoodEventsInWindow": 0,
        "category": "experimentation",
        "titleTemplate": "Try a {trigger} swap",
        "summaryTemplate": "Swapping {trigger} for 3 days could reduce your {symptom}.",
        "actionTemplate": "Try substituting {trigger} with a lighter alternative for the next 3 days. Use the HealthLab to track the results.",
        "whyTemplate": "We've detected a strong correlation between {trigger} and {symptom}. A short experiment can confirm if this swap helps.",
        "ctaType": "start_experiment",
        "ctaLabel": "Start Swap",
        "associatedExperimentId": None,
    },
    {
        "id": "trigger_avoidance_plan",
        "recommendationType": "prevention_plan",
        "applicablePatternTypes": ["symptom_correlation", "delayed_trigger"],
        "intensity": "high",
        "minPatternConfidence": "high",
        "minMealEventsInWindow": 12,
        "minMoodEventsInWindow": 0,
        "category": "planning",
        "titleTemplate": "Remove {trigger} temporarily",
        "summaryTemplate": "Removing {trigger} for 48 hours to test {symptom} impact.",
        "actionTemplate": "Try completely removing {trigger} from your diet for 48 hours. This 'mini-reset' can quickly reveal its impact on your {symptom}.",
        "whyTemplate": "The connection between {trigger} and your {symptom} is very consistent in your logs. A 48-hour break is a powerful way to verify this.",
        "ctaType": "set_goal",
        "ctaLabel": "Set Reset",
        "associatedExperimentId": None,
    },
    {
        "id": "mood_boost_habit",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": ["mood_boost"],
        "intensity": "low",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 5,
        "category": "habit_building",
        "titleTemplate": "Make {trigger} a habit",
        "summaryTemplate": "Incorporate more {trigger} into your routine.",
        "actionTemplate": "Since {trigger} often leads to better mood, try to include it in your meals at least 3 times this week.",
        "whyTemplate": "Building on positive correlations is the easiest way to improve consistency. Your data shows {trigger} is a winner!",
        "ctaType": "log_meal",
        "ctaLabel": "Plan Meal",
        "associatedExperimentId": None,
    },
    # ── Energy Dip ────────────────────────────────────────────────────────────
    {
        "id": "energy_dip_awareness",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": ["energy_dip_trigger"],
        "intensity": "low",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 3,
        "tags": ["energy", "awareness"],
        "category": "awareness",
        "titleTemplate": "Track your energy after {trigger}",
        "summaryTemplate": "We noticed a pattern between {trigger} and your energy. A few more logs will sharpen the signal.",
        "actionTemplate": "Next time you eat {trigger}, log your energy level 2–3 hours later. Consistent tracking will confirm if this is a real pattern.",
        "whyTemplate": "Your logs hint at a connection between {trigger} and low energy. A few more data points will confirm it.",
        "ctaType": "log_mood",
        "ctaLabel": "Log Energy",
        "associatedExperimentId": None,
    },
    {
        "id": "energy_dip_swap",
        "recommendationType": "substitution",
        "applicablePatternTypes": ["energy_dip_trigger"],
        "intensity": "medium",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 3,
        "tags": ["energy", "substitution"],
        "category": "experimentation",
        "titleTemplate": "Try swapping {trigger} for energy",
        "summaryTemplate": "Your energy often dips after eating {trigger}. One swap this week can test whether it makes a difference.",
        "actionTemplate": "Try replacing {trigger} with a lighter or higher-protein alternative once this week. Log your energy 2–3 hours later and compare.",
        "whyTemplate": "Your logs show a consistent link between {trigger} and low energy. A single controlled swap is a fast way to test it.",
        "ctaType": "start_experiment",
        "ctaLabel": "Try Swap",
        "associatedExperimentId": None,
    },
    # ── Sleep Impact ──────────────────────────────────────────────────────────
    {
        "id": "sleep_impact_awareness",
        "recommendationType": "soft_intervention",
        "applicablePatternTypes": ["sleep_impact_trigger"],
        "intensity": "low",
        "minPatternConfidence": "low",
        "minMealEventsInWindow": 5,
        "minMoodEventsInWindow": 3,
        "tags": ["sleep", "awareness"],
        "category": "awareness",
        "titleTemplate": "Watch {trigger} before bed",
        "summaryTemplate": "Your sleep quality appears to dip on nights when you eat {trigger} in the evening.",
        "actionTemplate": "On your next 3 evenings, note whether you eat {trigger} and log your sleep quality the next morning. Patterns become clearer quickly.",
        "whyTemplate": "Your logs show a link between {trigger} in the evening and poorer sleep. Awareness is the first step to testing whether removing it helps.",
        "ctaType": "log_mood",
        "ctaLabel": "Log Sleep",
        "associatedExperimentId": None,
    },
    {
        "id": "sleep_impact_timing",
        "recommendationType": "timing_intervention",
        "applicablePatternTypes": ["sleep_impact_trigger"],
        "intensity": "medium",
        "minPatternConfidence": "medium",
        "minMealEventsInWindow": 7,
        "minMoodEventsInWindow": 3,
        "tags": ["sleep", "timing"],
        "category": "behavioral_shift",
        "titleTemplate": "Move {trigger} earlier in the day",
        "summaryTemplate": "Eating {trigger} earlier — not later — may protect your sleep quality.",
        "actionTemplate": "For the next week, try eating {trigger} before 5 PM instead of in the evening. Log your sleep quality each morning to see if it improves.",
        "whyTemplate": "Your data suggests {trigger} in the evening is linked to poorer sleep. Shifting the timing (rather than eliminating it) is the lowest-friction test.",
        "ctaType": "start_experiment",
        "ctaLabel": "Shift Timing",
        "associatedExperimentId": None,
    },
]
